-- Add missing SecurityScanType enum values
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'SYSTEM_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'PROCESS_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'NETWORK_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'FILESYSTEM_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'SERVICE_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'CYBERPANEL_AUDIT';
ALTER TYPE "SecurityScanType" ADD VALUE IF NOT EXISTS 'PHP_AUDIT';
